#使用pickle

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
f = open('x.pkl','wb')

In [6]:
pickle.dump(x,f)

In [7]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [8]:
ls

 驱动器 D 中的卷没有标签。
 卷的序列号是 0F86-0FF6

 D:\jupyter_dir 的目录

2020/11/28  15:55    <DIR>          .
2020/11/28  15:55    <DIR>          ..
2020/11/28  15:53    <DIR>          .ipynb_checkpoints
2020/11/28  15:02             5,005 Array.ipynb
2020/11/28  15:55             2,372 Array的input和output.ipynb
2020/11/27  17:50               555 Untitled.ipynb
2020/11/28  15:54                 0 x.pkl
2020/11/28  15:36            16,531 数组与矩阵运算.ipynb
               5 个文件         24,463 字节
               3 个目录  6,428,217,344 可用字节


In [9]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [10]:
pwd

'D:\\jupyter_dir'

In [11]:
f = open('x.pkl','rb')

In [13]:
y = pickle.load(f)

In [14]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.save('one_array',x)

In [16]:
ls

 驱动器 D 中的卷没有标签。
 卷的序列号是 0F86-0FF6

 D:\jupyter_dir 的目录

2020/11/28  15:58    <DIR>          .
2020/11/28  15:58    <DIR>          ..
2020/11/28  15:53    <DIR>          .ipynb_checkpoints
2020/11/28  15:02             5,005 Array.ipynb
2020/11/28  15:57             4,610 Array的input和output.ipynb
2020/11/28  15:58               168 one_array.npy
2020/11/27  17:50               555 Untitled.ipynb
2020/11/28  15:57               187 x.pkl
2020/11/28  15:36            16,531 数组与矩阵运算.ipynb
               6 个文件         27,056 字节
               3 个目录  6,428,213,248 可用字节


In [17]:
x_test = np.load('one_array.npy')

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x_test

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
y = np.arange(20)

In [21]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.savez('two_array.npz', a=x, b=y)

In [23]:
ls

 驱动器 D 中的卷没有标签。
 卷的序列号是 0F86-0FF6

 D:\jupyter_dir 的目录

2020/11/28  16:00    <DIR>          .
2020/11/28  16:00    <DIR>          ..
2020/11/28  15:53    <DIR>          .ipynb_checkpoints
2020/11/28  15:02             5,005 Array.ipynb
2020/11/28  15:59             6,109 Array的input和output.ipynb
2020/11/28  15:58               168 one_array.npy
2020/11/28  16:00               610 two_array.npz
2020/11/27  17:50               555 Untitled.ipynb
2020/11/28  15:57               187 x.pkl
2020/11/28  15:36            16,531 数组与矩阵运算.ipynb
               7 个文件         29,165 字节
               3 个目录  6,428,200,960 可用字节


In [24]:
c = np.load('two_array.npz')

In [25]:
c

In [26]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])