# 数组的创建

In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4]

In [4]:
array_1 = np.array(l1)

In [5]:
array_1

array([1, 2, 3, 4])

In [6]:
array_2 = np.array([l1,[5,6,7,8]])

In [7]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
array_1.shape

(4,)

In [13]:
array_2.shape

(2, 4)

In [14]:
array_1.size

4

In [15]:
array_2.size

8

In [16]:
array_2.dtype

dtype('int32')

In [17]:
array_3 = np.array([1.0,2,3])

In [18]:
array_3.dtype

dtype('float64')

In [21]:
array_4 = np.arange(1,10,2)

In [22]:
array_4

array([1, 3, 5, 7, 9])

In [23]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
array_2[1,0]

5