In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([ 1.55205406,  1.61691096,  1.23463937, -1.67551832, -0.25915094,
       -0.45942959, -0.52556892, -0.39854578, -0.05076599, -1.3730808 ])

In [5]:
np.random.randint(10,size=(2,3))

array([[9, 4, 8],
       [9, 3, 2]])

In [9]:
np.random.randint(10,size=20)

array([6, 7, 4, 6, 6, 2, 8, 0, 0, 9, 2, 9, 7, 9, 6, 7, 3, 1, 0, 8])

In [10]:
np.random.randint(10,size=20).reshape(4,5)

array([[5, 6, 5, 8, 0],
       [0, 6, 5, 5, 5],
       [4, 8, 4, 8, 0],
       [3, 6, 9, 9, 8]])

In [11]:
a = np.random.randint(10,size=20).reshape(4,5)

In [12]:
b = np.random.randint(10,size=20).reshape(4,5)

In [13]:
a + b 

array([[ 8,  7,  9,  7,  9],
       [ 6, 10, 11,  2,  5],
       [ 8,  7, 11,  8,  8],
       [12, 13, 12,  7, 10]])

In [14]:
a

array([[5, 7, 5, 2, 9],
       [0, 7, 8, 0, 3],
       [4, 1, 6, 8, 5],
       [3, 8, 8, 0, 3]])

In [15]:
b

array([[3, 0, 4, 5, 0],
       [6, 3, 3, 2, 2],
       [4, 6, 5, 0, 3],
       [9, 5, 4, 7, 7]])

In [16]:
a - b

array([[ 2,  7,  1, -3,  9],
       [-6,  4,  5, -2,  1],
       [ 0, -5,  1,  8,  2],
       [-6,  3,  4, -7, -4]])

In [17]:
a * b

array([[15,  0, 20, 10,  0],
       [ 0, 21, 24,  0,  6],
       [16,  6, 30,  0, 15],
       [27, 40, 32,  0, 21]])

# 创建矩阵

In [18]:
np.mat(a)

matrix([[5, 7, 5, 2, 9],
        [0, 7, 8, 0, 3],
        [4, 1, 6, 8, 5],
        [3, 8, 8, 0, 3]])

# 矩阵运算

In [19]:
A = np.mat(a)

In [20]:
B = np.mat(b)

In [21]:
A + B

matrix([[ 8,  7,  9,  7,  9],
        [ 6, 10, 11,  2,  5],
        [ 8,  7, 11,  8,  8],
        [12, 13, 12,  7, 10]])

In [22]:
A - B

matrix([[ 2,  7,  1, -3,  9],
        [-6,  4,  5, -2,  1],
        [ 0, -5,  1,  8,  2],
        [-6,  3,  4, -7, -4]])

In [23]:
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [24]:
a = np.mat(np.random.randint(10,size=20).reshape(4,5))

In [25]:
b = np.mat(np.random.randint(10,size=20).reshape(5,4))

In [26]:
a * b

matrix([[ 82, 150, 196, 214],
        [ 14,  97,  60,  73],
        [ 94, 137, 202, 228],
        [ 99, 189, 238, 263]])

In [27]:
a

matrix([[5, 6, 4, 8, 7],
        [8, 2, 0, 0, 3],
        [3, 5, 6, 7, 9],
        [7, 7, 5, 9, 9]])

In [28]:
b

matrix([[0, 9, 4, 5],
        [4, 5, 5, 3],
        [7, 2, 8, 9],
        [2, 4, 9, 9],
        [2, 5, 6, 9]])

# Array

# Array 常用函数

In [29]:
a

matrix([[5, 6, 4, 8, 7],
        [8, 2, 0, 0, 3],
        [3, 5, 6, 7, 9],
        [7, 7, 5, 9, 9]])

In [30]:
a.unquire()

AttributeError: 'matrix' object has no attribute 'unquire'

In [31]:
a = np.random.randint(10,size=20).reshape(4,5)

In [32]:
a

array([[3, 5, 0, 0, 8],
       [9, 0, 0, 3, 6],
       [1, 9, 3, 5, 4],
       [5, 6, 3, 5, 3]])

In [33]:
a.unquire()

AttributeError: 'numpy.ndarray' object has no attribute 'unquire'

In [34]:
np.unicode(a)

'[[3 5 0 0 8]\n [9 0 0 3 6]\n [1 9 3 5 4]\n [5 6 3 5 3]]'

In [35]:
np.unique(a)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [36]:
sum(a)

array([18, 20,  6, 13, 21])

In [37]:
sum(sum(a))

78

In [38]:
sum(a[:][0])

16

In [39]:
a.max

<function ndarray.max>

In [40]:
a.max()

9